FROM node:20-alpine AS build

WORKDIR /app/frontend

ARG  VITE_API_URL   
ENV  VITE_API_URL=${VITE_API_URL}

COPY frontend/package*.json ./

RUN npm ci



COPY  frontend .
COPY shared ../shared

RUN npm run build

FROM  nginx:stable-alpine

RUN rm -rf /usr/share/nginx/html

COPY --from=build /app/frontend/dist /usr/share/nginx/html

COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD  ["nginx","-g", "daemon off;"]


